"""End-to-end ATAF server demo — the circle-area tool, no LLM required.

This script exercises the full server-side acquisition loop over plain
HTTP, exactly as an agent would, but with the tool code written by hand
instead of generated by an LLM (the LLM-driven agent client lands in a
later v0.1 session). It demonstrates:

    1. GET /tools                 — the catalog starts empty
    2. POST /tools/propose        — deploy circle_area (→ PENDING_REVIEW)
    3. POST /tools/{id}/invoke    — refused 403 while pending
    4. POST /admin/.../approve    — a human authorizes it
    5. POST /tools/{id}/invoke    — now returns the area

Run it against a server you started separately, e.g.:

    ATAF_PORT=9123 ataf-server         # in one terminal
    python examples/circle_area/demo.py    # in another

Override the target with ATAF_BASE_URL (default http://127.0.0.1:9123).
"""

from __future__ import annotations

import os

import httpx


# The tool the "LLM" proposes — the canonical worked example from the
# design doc. Stdlib-only, fully typed, Google-style docstring.
CIRCLE_AREA_CODE = '''def circle_area(radius: float) -> float:
    """Compute the area of a circle.

    Args:
        radius: The radius of the circle, in any unit.

    Returns:
        The area in the squared unit of the radius.
    """
    import math
    return math.pi * radius ** 2
'''


def main() -> None:
    """Walk the propose → approve → invoke loop and print each step."""

    base_url = os.environ.get("ATAF_BASE_URL", "http://127.0.0.1:9123")
    client = httpx.Client(base_url=base_url, timeout=35.0)

    # 1. The catalog starts empty on a fresh server.
    catalog = client.get("/tools").json()
    print(f"[1] catalog has {len(catalog['tools'])} tool(s) "
          f"(version {catalog['catalog_version']})")

    # 2. Propose the new tool. The server validates, builds, and deploys
    # it as PENDING_REVIEW, returning the generated schema.
    proposal = client.post(
        "/tools/propose",
        json={"intent": "compute the area of a circle", "code": CIRCLE_AREA_CODE},
    ).json()
    tool_id = proposal["tool_id"]
    print(f"[2] deployed {tool_id} "
          f"(status {proposal['tool_status']})")
    print(f"    input_schema: {proposal['input_schema']}")

    # 3. Try to invoke it while still pending — the server refuses (403),
    # demonstrating Layer-2 governance enforcement.
    pending_call = client.post(
        f"/tools/{tool_id}/invoke", json={"args": {"radius": 10}}
    )
    print(f"[3] invoke while pending -> HTTP {pending_call.status_code}: "
          f"{pending_call.json().get('error')}")

    # 4. A human approves the tool (here via the admin HTTP endpoint; the
    # ataf-admin CLI does the same thing directly against the registry).
    client.post(f"/admin/tools/{tool_id}/approve")
    print(f"[4] approved {tool_id}")

    # 5. Invoke again now that it's AUTHORIZED — this returns the result.
    result = client.post(
        f"/tools/{tool_id}/invoke", json={"args": {"radius": 10}}
    ).json()
    print(f"[5] circle_area(radius=10) = {result['result']}")

    client.close()


if __name__ == "__main__":
    main()
